apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutlass-deployment
  namespace: project
  labels:
    app: cutlass-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cutlass-app
  template:
    metadata:
      name: cutlass-app
      labels:
        app: cutlass-app
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: cutlass-pv-claim
      containers:
        - name: cutlass-app
          image: matsubokkuri/cutlass-app:2.6
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-storage
              mountPath: /usr/src/app/files
          env:
            - name : TODO_URL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: cutlass-config
                  key: todo_url_address
            - name : IPSUM_PIC_SP_URL
              valueFrom:
                configMapKeyRef:
                  name: cutlass-config
                  key: ipsum_pic_sp_url
            - name : APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: cutlass-config
                  key: app_port
        - name: cutlass-backend
          image: matsubokkuri/cutlass-backend:2.6
          env:
            - name : BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: cutlass-config
                  key: backend_port
          imagePullPolicy: Always
      restartPolicy: Always
      