apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cutlass-ingress
  namespace: project
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cutlass-app-svc
                port:
                  number: 2345
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: cutlass-backend-svc
                port:
                  number: 2346
