apiVersion: v1
kind: Service
metadata:
  name: cutlass-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: cutlass-app
  ports:
    - name: cutlass-app
      port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cutlass-backend-svc
spec:
  type: ClusterIP
  selector:
    app: cutlass-app
  ports:
    - name: cutlass-backend
      port: 2346
      protocol: TCP
      targetPort: 3010