apiVersion: v1
kind: Service
metadata:
  name: cutlass-app-svc
spec:
  type: ClusterIP
  selector:
    app: cutlass-app
  ports:
    - name: cutlass-app
      port: 2345
      protocol: TCP
      targetPort: 3000