apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cutlass-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cutlass-app-svc
                port:
                  number: 2345
          - path: /hashtime
            pathType: Prefix
            backend:
              service:
                name: cutlass-app-svc
                port:
                  number: 2345
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: woodboard-app-svc
                port:
                  number: 2346
