apiVersion: v1
kind: Service
metadata:
  name: cutlass-app-svc
spec:
  type: NodePort
  selector:
    app: cutlass-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000