apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scimitar-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scimitar-app-svc
                port:
                  number: 2345
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: scimitar-backend-svc
                port:
                  number: 2346
          - path: /pings
            pathType: Prefix
            backend:
              service:
                name: scimitar-backend-svc
                port:
                  number: 2346
