apiVersion: v1
kind: Service
metadata:
  name: scimitar-app-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: scimitar-app
  ports:
    - name: scimitar-app
      port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: scimitar-backend-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: scimitar-app
  ports:
    - name: scimitar-backend
      port: 2346
      protocol: TCP
      targetPort: 3010


