apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutlass-deployment
  labels:
    app: cutlass-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cutlass-app
  template:
    metadata:
      name: cutlass-app
      labels:
        app: cutlass-app
    spec:
      containers:
        - name: cutlass-app
          image: matsubokkuri/cutlass-app:1.2
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      